/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JS' at '16. 8. 21 오후 3:20' with Gradle 3.0
 *
 * @author JS, @date 16. 8. 21 오후 3:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
